version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - run:
          name: clone  backend
          command: git clone https://github.com/guydied/labo1-backend.git 
      - run:
          name: Installation de dependances
          command: |
            cd labo1-backend 
            npm install
      - run:
          name: Tests
          command: |
            cd labo1-backend 
            npm run test
  integrationFrontend:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - run:
          name: clone  frontend
          command: git clone https://github.com/guydied/labo1-frontend.git
      - run:
          name: clone backend
          command: git clone https://github.com/guydied/labo1-backend.git
      - run:
          name: Installation de dependances frontend
          command: |
            cd labo1-frontend 
            npm install
      - run:
          name: build frontend
          command: |
            cd labo1-frontend
            npm run build
      - run:
          name: Creation du r√©pertoir public dans backend
          command: |
            cd labo1-backend
            mkdir -p public
      - run:
          name: Copie des fichiers build du frontend dans public du backend
          command: cp -rT labo1-frontend/build labo1-backend/public/
      - persist_to_workspace:
          root: .
          paths:
            - labo1-backend
  deploiement:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Commande dans le backend provenant du workspace
          command: |
            cd labo1-backend
            ls -Rl 

workflows:
  build:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend